language: objective-c
osx_image: xcode7.2
before_install:
- brew update > /dev/null
- brew install carthage > /dev/null
before_script:
- carthage bootstrap
script:
- xctool -project "SwiftLogging.xcodeproj" -scheme "SwiftLogging_OSX" build test
- xctool -project "SwiftLogging.xcodeproj" -scheme "SwiftLogging_iOS" -sdk iphonesimulator build test
- xctool -project "SwiftLogging.xcodeproj" -scheme "GUI" build test
- xctool -project "SwiftLogging.xcodeproj" -scheme "GUI_iOS" -sdk iphonesimulator build test

