language: objective-c
osx_image: xcode7.2
before_script:
- carthage bootstrap --no-use-binaries
script:
- xcodebuild -project "SwiftLogging.xcodeproj" -scheme "SwiftLogging_OSX" build
- xcodebuild -project "SwiftLogging.xcodeproj" -scheme "SwiftLogging_iOS" -sdk iphonesimulator build
- xcodebuild -project "SwiftLogging.xcodeproj" -scheme "GUI" build
- xcodebuild -project "SwiftLogging.xcodeproj" -scheme "GUI_iOS" -sdk iphonesimulator build

